style_edition = "2021"
imports_granularity = "Crate"
# unstable features: use cargo +nightly fmt
group_imports = "StdExternalCrate"
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
use_field_init_shorthand = true
