[package]
name = "openvm-algebra-moduli-macros"
version = { workspace = true }
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
openvm-macros-common = { workspace = true, default-features = false }

[lib]
proc-macro = true