[package]
name = "openvm-rv32im-guest"
description = "OpenVM guest library for RISC-V 32-bit IM instruction set"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-custom-insn = { workspace = true }
strum_macros = { workspace = true }

[features]
default = []
