[package]
name = "openvm-ecc-circuit"
description = "OpenVM circuit extension for elliptic curve cryptography"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-circuit-primitives-derive = { workspace = true }
openvm-circuit-primitives = { workspace = true }
openvm-circuit-derive = { workspace = true }
openvm-circuit = { workspace = true }
openvm-instructions = { workspace = true }
openvm-mod-circuit-builder = { workspace = true }
openvm-stark-backend = { workspace = true }
openvm-rv32im-circuit = { workspace = true }
openvm-algebra-circuit = { workspace = true }
openvm-rv32-adapters = { workspace = true }
openvm-ecc-transpiler = { workspace = true }

num-bigint = { workspace = true }
num-traits = { workspace = true }
strum = { workspace = true }
derive_more = { workspace = true }
derive-new = { workspace = true }
once_cell = { workspace = true, features = ["std"] }
serde = { workspace = true }
serde_with = { workspace = true }
lazy_static = { workspace = true }
hex-literal = { workspace = true }

[dev-dependencies]
openvm-stark-sdk = { workspace = true }
openvm-mod-circuit-builder = { workspace = true, features = ["test-utils"] }
openvm-circuit = { workspace = true, features = ["test-utils"] }
openvm-rv32-adapters = { workspace = true, features = ["test-utils"] }
lazy_static = { workspace = true }
