[package]
name = "openvm-algebra-guest"
description = "OpenVM guest library for algebra over rings and fields, including modular and complex field arithmetic."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm = { workspace = true }
openvm-platform = { workspace = true }
openvm-algebra-moduli-setup = { workspace = true }
openvm-algebra-complex-macros = { workspace = true }
serde = { workspace = true }
serde-big-array = "0.5.1"
strum_macros = { workspace = true }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
num-bigint-dig.workspace = true
halo2curves-axiom = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = []
std = []
halo2curves = ["dep:halo2curves-axiom"]
