[package]
name = "openvm-rv32-adapters"
description = "OpenVM adapters for rv32 intrinsics"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-stark-backend = { workspace = true }
openvm-stark-sdk = { workspace = true }
openvm-circuit-primitives = { workspace = true }
openvm-circuit-primitives-derive = { workspace = true }
openvm-circuit = { workspace = true }
openvm-rv32im-circuit = { workspace = true }
openvm-instructions = { workspace = true }

itertools.workspace = true
tracing.workspace = true
derive-new.workspace = true
rand.workspace = true

[dev-dependencies]
openvm-stark-sdk = { workspace = true }
test-case.workspace = true
test-log.workspace = true
lazy_static.workspace = true
openvm-circuit = { workspace = true, features = ["test-utils"] }
hex.workspace = true

[features]
default = ["parallel"]
parallel = ["openvm-circuit/parallel"]
test-utils = ["openvm-circuit/test-utils"]
