[package]
name = "openvm-poseidon2-air"
description = "Wrapper for the Plonky3 Poseidon2 AIR."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
p3-monty-31 = { workspace = true }
p3-symmetric = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-poseidon2-air = { workspace = true }
zkhash = { workspace = true }

openvm-circuit-primitives = { workspace = true }
openvm-stark-backend = { workspace = true }
openvm-stark-sdk = { workspace = true }

rand.workspace = true
lazy_static.workspace = true
itertools.workspace = true
tracing.workspace = true
derivative.workspace = true

[dev-dependencies]
p3-symmetric = { workspace = true }
test-case = "3.3.1"
ark-ff = { version = "^0.4.0", default-features = false }

[features]
default = ["parallel"]
parallel = ["openvm-stark-backend/parallel"]
