name: DB Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "stark-backend/**"
      - "primitives/**"
      - "db/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  AXIOM_FAST_TEST: "1"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run DB unit tests
        working-directory: db/page
        run: |
          cargo t --features parallel

  benchmark-rw:
    uses: ./.github/workflows/benchmark-call.yml
    if: github.event.pull_request.draft == false
    with:
      benchmark_name: single_rw
    secrets: inherit

  benchmark-filter:
    uses: ./.github/workflows/benchmark-call.yml
    if: github.event.pull_request.draft == false
    with:
      benchmark_name: single_filter
    secrets: inherit
