name: Primitives Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - "crates/circuits/primitives/**"
      - "crates/circuits/poseidon2-air/**"
      - "crates/circuits/sha256-air/**"
      - "Cargo.toml"
      - ".github/workflows/primitives.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENVM_FAST_TEST: "1"

jobs:
  build:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=32cpu-linux-arm64
      - extras=s3-cache

    steps:
      - uses: runs-on/action@v1
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest

      - name: Run tests for primitives
        working-directory: crates/circuits/primitives
        run: |
          cargo nextest run --cargo-profile fast --features parallel

      - name: Run tests for poseidon2-air
        working-directory: crates/circuits/poseidon2-air
        run: |
          cargo nextest run --cargo-profile fast --features parallel

      - name: Run tests for sha256-air
        working-directory: crates/circuits/sha256-air
        run: |
          cargo nextest run --cargo-profile fast --features parallel
